Improve usage and displaying of errors.

diff --git a/git-delete-merged b/git-delete-merged
--- a/git-delete-merged
+++ b/git-delete-merged
@@ -6,43 +6,49 @@ set -uo pipefail
 # operate in dryrun mode
 dry_run=1
 
-##  Usage: @script.name [--apply] <[--local] | --remote <remote>> [--branches-to-skip <branches to skip>]
-##
-##  Example to delete all branches on GitHub matching 'patch-':
-##          git-delete-merged --apply --remote github --match patch-
-##
-##  Options:
-##      -d, --appl              Execute the plan.
-##      -l, --local             Operate on local branches
-##      --remote=my-remote      Operate on remote branches on the remote repo
-##      --skip=branches         The list of branches to skip. Default is "master,develop"
-##      --match=<regex>         Only delete branch names matching <regex>
-##      --merge-master=branch   Branch to use as the master when deciding if a branch has been merged. Default 'origin/master'
-##
-##  By default, "master" and "develop" are skipped
-##  Specifying x-delete-tool.protected-branches in your git config, or
-##  listing them on the command line with commas will override this
-##
-##  Likewise, you can store a permanent override for what constitutes
-##  the main branch by setting the x-delete-tool.merge-master property
-##  Example:
-##  git config --add x-delete-tool.merge-branch origin/develop
+usage(){
+cat <<- EOF
+
+
+$0 [--apply] (--local|--remote <remote_name>) [--skip <branches,to,skip>] [--match <regex>] [--ignore <regex>] --into <branch (default:master)>"
+
+Example to delete all branches on GitHub matching 'patch-':
+
+        git-delete-merged --apply --remote github --match 'patch-.*'
+
+Options:
+    --apply                 Execute the plan.
+    --local                 Operate on local branches
+    --remote=my-remote      Operate on remote branches on the remote repo
+    --skip=branches         The list of branches to skip. Default is "master,develop"
+    --match=<regex>         Only delete branch names matching <regex>
+    --ignore=<regex>        Ignore branches matching <regex>
+    --merge-master=branch   Branch to use as the master when deciding if a branch has been merged. Default 'origin/master'
+
+By default, "master" and "develop" are skipped Specifying x-delete-tool.protected-branches in your git config, or listing them on the command line with commas will override this Likewise, you can store a permanent override for what constitutes the main branch by setting the x-delete-tool.merge-master property.
+
+Example:
+
+    git config --add x-delete-tool.merge-branch origin/develop
+
+
+EOF
+
+exit 1
+}
 
 # general helper
-ferr() {
-    echo "$*"
-    exit 1
-}
-
 echo_err() {
-    echo "$*" 1>&2
+    echo
+    echo "$(tput bold)$(tput setaf 1)ERROR:$(tput sgr0)$(tput bold) $* $(tput sgr0)" 1>&2
 }
 
-# script specific helper
-usage(){
-    echo "$0 [--apply] (--local|--remote <remote_name>) --skip <branches,to,skip> --into <branch (default:master)>"
+ferr() {
+    echo_err "$*"
+    usage
     exit 1
 }
+
 
 parse_options() {
     arg_apply=false
@@ -89,8 +95,7 @@ parse_options() {
                 arg_remote=0
             ;;
             *)
-                echo "invalid argument: '$1'"
-                usage
+                ferr "invalid argument: '$1'"
             ;;
             esac
         shift
@@ -101,8 +106,7 @@ parse_options() {
 validate_config() {
     dry_run=true
     if ! (( arg_remote ^ arg_local )); then
-        echo "ERROR: you need to specify '--remote' or '--local'"
-        usage
+        ferr "you need to specify '--remote' or '--local'"
     fi
 
     if (( arg_local == 1 )); then
@@ -114,8 +118,7 @@ validate_config() {
     if (( arg_remote == 1 )); then
         arg_remote=true
         if [[ -z $arg_remote_name ]]; then
-            echo "you did not supply a remote name"
-            usage
+            ferr "you did not supply a remote name"
         fi
     else
         arg_remote=false
